### PR TITLE
Publish on release

### PR DESCRIPTION
**Pull request by dignite**
# How to set up

- Log in and enable Travis for the repository.
- Change `deploy.api_key.secure` in `.travis.yml` by getting a [github personal access token](https://github.com/settings/tokens) and [encrypting it with travis cli](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml), then commit it.

# How to use

By creating a release in github, travis will build and attach the built apps to that release.

[Example release v13.3.7](https://github.com/dignite/mob-timer/releases/tag/v13.3.7)

## Steps

1. Go to Github Releases for the Repository
    
1. Create a new Github Release
    
1. Release is now created
    
1. This triggers a build in Travis CI
    
1. Grab a ☕️ 
1. Come back to a successful build
    
1. Refresh the Github Release
    
1. Enjoy 🎉

### CODE REVIEW

**Comment by allan-stewart** [comment]
The idea is solid (though we'd need to figure out our versioning / tagging strategy). However, I am _extremely_ uncomfortable with the level of access that TravisCI requires to even create an account. Especially given that the `pluralsight` org on GitHub hosts a number of public private repositories, not just our open-source mob-timer.

**Comment by dignite** [comment]
I agree with your concern, it is not nice. A work around is to create a dedicated github machine user (just a regular user) and only give it access to the mob timer repo, then generate the oauth on that. Would you be open to trying that?

**Comment by dignite** [comment]
The work around is [suggested by Travis CI](https://docs.travis-ci.com/user/deployment/releases#authenticating-with-an-oauth-token)

**Comment by dignite** [comment]
@mob-timer

**Comment by allan-stewart** [comment]
FYI, I haven't forgotten about this, but it's pretty low priority for me at the moment. The machine user workaround seems like it would be acceptable, but I'd have to coordinate with our Operations team to get that set up, and I just haven't had the time to get that done yet.

**Pull request closed without merging**
